name: generate plantuml
on: push

jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: plantuml
        id: plantuml
        uses: BlackCat1968/generate-plantuml-action@v1.5-node24
        with:
          path: example
          message: "Render PlantUML files"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
